spring.application.name=CRUD
spring.datasource.url=jdbc:mysql://shuttle.proxy.rlwy.net:19949/railway?sslMode=REQUIRED
spring.datasource.username=root
spring.datasource.password=RhxNtdbvQCvbwAEvbCEYUfKfUAaWTesx
spring.jpa.hibernate.ddl-auto=update

spring.main.banner-mode=off

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

spring.mail.host=smtp-relay.brevo.com
spring.mail.username=7e4736001@smtp-brevo.com
spring.mail.password=ODI5swcGZkXMRqxa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true
spring.jpa.properties.hibernate.format_sql=true

jwt.secret.key=graduationprojectcsforsmartsteerapp


#spring.cache.type=redis
#spring.redis.url=${REDIS_URL}
#spring.redis.host=localhost
#spring.redis.port=6379

# --- Caching ---
spring.cache.type=redis

# --- Redis Configuration for External Redis Cloud (LOCAL TEST) ---
spring.redis.host=safe-piglet-54061.upstash.io
spring.redis.port=6379
spring.redis.password=AdMtAAIjcDE4MDU3ZGViMjU0ZDY0NzhhYmEzOTczYzJkNGUyMjUxYnAxMA
spring.redis.ssl=true # Set explicitly based on redis-cli test

# Optional: Adjust timeout if needed
spring.redis.timeout=10000

# Optional: Keep pool settings
spring.redis.lettuce.pool.max-active=8
spring.redis.lettuce.pool.max-wait=-1



