spring.application.name=my-spring-boot-app

spring.cloud.gcp.project-id=green-carrier-459312-n9
spring.cloud.gcp.sql.instance-connection-name=green-carrier-459312-n9:europe-west1:ss2025
spring.cloud.gcp.sql.database-name=smartsteer_data

spring.datasource.username=root
spring.datasource.password=sm://db-password

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

management.endpoints.web.exposure.include=health,info
management.endpoint.health.show-details=always

spring.main.banner-mode=off

logging.level.org.springframework.security=DEBUG
logging.level.org.springframework=INFO
logging.level.org.hibernate.SQL=INFO
logging.level.org.hibernate.type.descriptor.sql.BasicBinder=WARN


spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.mode=HTML
spring.thymeleaf.encoding=UTF-8
spring.thymeleaf.cache=false

spring.mail.host=smtp-relay.brevo.com
spring.mail.username=7e4736001@smtp-brevo.com
spring.mail.password=ODI5swcGZkXMRqxa
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true


jwt.secret.key=graduationprojectcsforsmartsteerapp

spring.datasource.hikari.maximum-pool-size=10
spring.datasource.hikari.minimum-idle=2
spring.datasource.hikari.idle-timeout=30000
spring.datasource.hikari.connection-timeout=20000

server.compression.enabled=true
server.compression.mime-types=text/html,text/xml,text/plain,application/json
server.compression.min-response-size=100
